# Generated by Django 3.1.7 on 2021-03-30 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='fileUuidMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_hash', models.CharField(max_length=512)),
                ('content_length', models.SmallIntegerField()),
                ('system_path', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='onionCrawlerEngine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_name', models.CharField(max_length=50)),
                ('engine_url', models.CharField(max_length=512)),
                ('status_code', models.SmallIntegerField()),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='detectKeywords',
            fields=[
                ('keyword', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='detectedUrl',
            fields=[
                ('onion_http_hash', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('onion_http', models.URLField(max_length=1024)),
                ('mirror_http', models.URLField(max_length=2048)),
                ('content_length', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lastChecked_at', models.DateTimeField(auto_now_add=True)),
                ('status_code', models.SmallIntegerField()),
                ('title', models.CharField(max_length=512)),
                ('referer', models.CharField(max_length=50)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.detectkeywords')),
            ],
        ),
    ]
